apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
  labels:
    app: simpleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
        - name: simpleapp
          image: jonnyff/simpleapp-python:1.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: simpleapp-cm
          ports:
          - containerPort: 8008
      imagePullSecrets:
      - name: regcred